### ISSUE TITLE
Reference Assemblies for .NET Framwork 3.5

### ISSUE THREAD

**Issue by krafs** [microsoft/dotnet#1137] opened 2019-11-06 06:54 UTC
Are there any plans to add reference assemblies for .NET Framework 3.5 into `Microsoft.NETFramework.ReferenceAssemblies`?

**Comment by gjuttla** [comment] 2019-12-12 09:47
Unfortunately, it does not seem like that based on the comments on dotnet/core-sdk#2022.
But there is a package available by @jnm2 to support .NET Framework 3.5 reference assemblies: https://www.nuget.org/packages/jnm2.ReferenceAssemblies.net35

**Comment by jnm2** [comment] 2019-12-12 13:23
It appears to be an arbitrary policy decision since no technical limitations have come to light. I'm not sure where it originates, but it is communicated to us by Immo Landwerth at https://github.com/dotnet/designs/pull/33#issuecomment-557716786:

> > Why not? And why is dotnet/core-sdk#2022 still active then?
> 
> Because our general policy is that we don't add new features to support older versions of the .NET platform. The reason we're supporting .NET Framework 2.0 is rooted in internal requirements driven by the compiler team. Otherwise we would have cut off at 4.5, which is what the spec originally suggested

**Comment by krafs** [comment] 2019-12-19 20:10
The NuGet by @jnm2 seems to work well, so I'm content. I understand one has to draw the line for legacy software somewhere, but people obviously come up with unofficial solutions anyway, so why not just release an official package to go along with the other ones? Anyway, thanks!

**Comment by RussKie** [comment] 2019-12-20 01:12
I have no stakes here, just my 2c. Even biggest companies don't have infinite resources. To release "just another package" means there have to be extra resources assigned to this (likely multiple people, build pipelines, storage) and the package has to undergo verifications, and, once we ship it, we need to provide support for it as well.

What our customer (like yourself) see is just a tip of the iceberg, building and shipping the framework is an intensely involved process. And that's why we need to draw lines somewhere. Even though these lines may look arbitrary.

**Comment by rstm-sf** [comment] 2021-04-15 19:29
Another option https://www.nuget.org/packages/JetBrains.NETFramework.ReferenceAssemblies.net35/

**Comment by NikolaMilosavljevic** [comment] 2021-04-22 18:01
@krafs, was this closed by accident? The issue is still assigned to me and being considered.

**Comment by KirillOsenkov** [comment] 2021-04-22 18:03
Yes, please, let's not close this and still fix this if at all possible.

**Comment by krafs** [comment] 2021-04-22 18:05
I'm sorry, I got the impression the issue had been abandoned. My bad.

**Comment by jnm2** [comment] 2021-04-22 18:07
I had the same impression.

**Comment by NikolaMilosavljevic** [comment] 2021-05-05 22:42
New version of .NET reference assembly nuget packages have just been published to nuget.org. It includes .NET 3.5 😃 

https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies/

**Comment by jnm2** [comment] 2021-05-05 23:12
@NikolaMilosavljevic I see a problem with the net35 that was fixed on request by a user of jnm2.ReferenceAssemblies.net35. The casing on one filename is `System.configuration.dll` and this causes it to fail to load on non-Windows OSs.

**Comment by NikolaMilosavljevic** [comment] 2021-05-05 23:34
> @NikolaMilosavljevic I see a problem with your net35 package that was fixed on request by a user of jnm2.ReferenceAssemblies.net35. The casing on one filename is `System.configuration.dll` and this causes it to fail to be found on non-Windows OSs.

Thanks @jnm2 - I'll work on a fix.

**Comment by bording** [comment] 2021-05-05 23:58
Since the SDK now adds an implicit reference to the reference assemblies package as needed, is there something that needs to be done on that side for it to use the new version, or will that be picked up automatically?

**Comment by jnm2** [comment] 2021-05-06 00:03
Looks like the version is hardcoded to 1.0.0, but you can override it yourself or just specify the package reference. I would like to know if .NET 6 will update that version to 1.0.2 (containing the fix that @NikolaMilosavljevic is working on).

https://github.com/dotnet/sdk/blob/v6.0.100-preview.3.21201.24/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.props#L104

**Comment by NikolaMilosavljevic** [comment] 2021-05-06 00:22
I think we would need to prepare the PR to rev the reference in .NET SDK. @dsplaisted do you know if this would be the right model?

**Comment by NikolaMilosavljevic** [comment] 2021-05-07 20:12
Version 1.0.2 has been published - it includes the fix for filename casing of System.Configuration.dll assembly. @dsplaisted can we get the version updated in sdk?

**Closed** 2021-05-10 22:48 UTC
