### ISSUE TITLE
.NET 4.7 problem with WCF service reference.

### ISSUE THREAD

**Issue by urza** [Microsoft/dotnet#433] opened 2017-06-29 06:33 UTC
I have asp.net mvc project targeting .NET 4.5
I tried to update to .NET 4.7 but there is problem with web service that my mvc project is consuming. The service is WCF defined with http://xxx.svc endpoint. You can see on screenshot 1 that with .NET 4.5 it is fine, I can consume this service:

![1_45ok](https://user-images.githubusercontent.com/189804/27674255-36dbd1ea-5ca5-11e7-9e21-7ac756c0f916.PNG)

However after updating my project to .NET 4.7 the service reference no loger works, the parts of my code referencing it can't see it. I tried to "UpdateServiceReference" - no change. I tried to delete the service and add it again from the .svc endpoint, doesnt work either.

![2_47broken](https://user-images.githubusercontent.com/189804/27674322-747ca916-5ca5-11e7-9243-3b39623f5793.PNG)

**Comment by richlander** [comment] 2017-07-03 01:34
@dagood @StephenBonikowsky can you help?

/cc @preetikr

**Comment by StephenBonikowsky** [comment] 2017-07-03 16:51
@zhenlan

**Comment by zhenlan** [comment] 2017-07-03 17:42
> I tried to delete the service and add it again from the .svc endpoint, doesnt work either.

@urza sorry for running into this. By "doesn't work", did you mean the tool fail to generate service reference or the generated service reference does not compile? Just to isolate the issue - did you try to create a new MVC app from VS template and add service reference again to see if works? By any chance can you share a repo project with us? That will be very helpful for our investigation.

**Comment by zhenlan** [comment] 2017-07-05 18:05
@urza we tried to upgrade an MVC project with service reference from 4.5 to 4.7 but cannot reproduce the issue you saw, so it might be related to something more specific to your project or the service. BTW, if you change your project back to 4.5, will the issue go away?

**Comment by zhenlan** [comment] 2017-07-26 21:27
Closing for now. @urza please let me know if you have further information.

**Closed by zhenlan** 2017-07-26 21:27 UTC

**Comment by cblaze22** [comment] 2017-08-05 00:34
I have same issue, upgraded from 4.6.1 to 4.7 and now I can't regenerate my web service.

**Comment by zhenlan** [comment] 2017-08-05 03:24
@cblaze22 sorry for running into this. Do you have any information regarding the questions I asked on [Jul 3](https://github.com/Microsoft/dotnet/issues/433#issuecomment-312701957) and [Jul 5](https://github.com/Microsoft/dotnet/issues/433#issuecomment-313181260) above? It will be very helpful if you can can share any further information.

**Comment by cblaze22** [comment] 2017-08-05 03:40
I had to uncheck "Reuse types in all reference assemblies" and check "mscorlib" to make it work.

![capture](https://user-images.githubusercontent.com/556494/28992572-21eab31a-796e-11e7-9b35-1e878c6d12f5.PNG)

**Comment by clawfrank** [comment] 2019-07-26 19:17
Is that the intended solution? It works, but why? Seems like it should be re-opened.
