### ISSUE TITLE
FileSystemWatcher Notifications / Wait for Completion

### ISSUE THREAD

**Issue by JohnLBevan** [Microsoft/dotnet#437] opened 2017-07-10 16:50 UTC
There seems to be a common scenario where people use the FileSystemWatcher to trigger an action upon a file's creation.  However, as this trigger is fired when the file starts to be created, rather than once that process completes (and thus the file is complete / the lock is removed), people have often had to write custom code to loop, checking whether the file's locked, before eventually performing some action on it.

Examples: 
- https://www.intertech.com/Blog/avoiding-file-concurrency-using-system-io-filesystemwatcher/
- https://stackoverflow.com/questions/44583244/copy-item-does-not-work

One possible solution would be to have another NotifyFilter which could trigger the FileSystemWatcher event once the file had been fully written to; or once locks were removed.

Example code illustrating the current workaround quoted from above InterTech blog:

```

class WatcherService
{
    System.IO.FileSystemWatcher watcher;
    public WatcherService()
    {
        watcher = new System.IO.FileSystemWatcher();
        watcher.EnableRaisingEvents = true;
        watcher.Filter = "*.zip";
        watcher.NotifyFilter = System.IO.NotifyFilters.LastWrite;
        watcher.Changed += new System.IO.FileSystemEventHandler(FileChanged);
    }

    private void FileChanged(object sender, FileSystemEventArgs e)
    {
        if (!IsFileReady(e.FullPath)) return; //first notification the file is arriving

        //The file has completed arrived, so lets process it
        DoWorkOnFile(e.FullPath);
    }

    private bool FileIsReady(string path)
    {
        //One exception per file rather than several like in the polling pattern
        try
        {
             //If we can't open the file, it's still copying
             using (var file = File.Open(path, FileMode.Open, FileAccess.Read, FileShare.Read))
             {
                 return true;
             }
        }
        catch (IOException)
        {
             return false;
        }
    }
}

```

**Comment by jnm2** [comment] 2017-07-10 18:32
The problem is that there is an inherent race condition. Even if you were notified as soon as there were no locks, by the time your process tries to open the file, another process may have locked it.

The only safe (atomic) solution is to repeatedly try to open it an catch the IOException that occurs. That way, when the IO exception does not occur, you're already holding onto an open file and no race condition with another process is possible.

(Same thing applies to file existence checks too, incidentally.)

**Comment by jnm2** [comment] 2017-07-10 18:33
And you can't close the file and reopen it in subsequent code, or you're back to race condition land.

**Comment by jnm2** [comment] 2017-07-10 18:33
In that case you need to pass the FileStream around your code, not the path.

**Comment by jnm2** [comment] 2017-07-10 18:36
If the FileSystemWatcher provided a way to hand you an open FileStream to the file you're watching for, that would avoid the race condition and be awesome. But it also feels like it belongs in a separate component.

**Comment by JohnLBevan** [comment] 2017-07-11 16:21
Ah, that's an excellent point @jnm2; not something I'd considered.  
Your suggestion of providing a stream is perfect; though as you state, that would be new functionality; not an amendment to the existing implementation.  
I'll leave this issue open as a suggestion for that new functionality; unless anyone objects?

**Comment by richlander** [comment] 2017-07-15 03:30
API design proposals/requests should be posted at [dotnet/corefx](https://github.com/dotnet/corefx/issues). Thanks.

**Comment by Petermarcu** [comment] 2017-10-19 21:01
As @richlander stated, dotnet/corefx is the place to have the discussion about this API. Go ahead an open a proposal there if you want to take this forward. Closing this one here.

**Closed by Petermarcu** 2017-10-19 21:02 UTC
