### ISSUE TITLE
.NET 4.7.1 Grid star sizing causes hang in ResolveStarMaxDiscrepancy

### ISSUE THREAD

**Issue by brinko99** [microsoft/dotnet#604] opened 2018-01-27 01:15 UTC
I'm seeing another Grid hanging issue in 4.7.1 regarding WPF Grid star sizing column widths.

Specifically `ResolveStarMaxDiscrepancy` seems to hang or get into some sort of infinite loop under certain conditions. The below Window reproduces the problem; slowly reduce the width of the Window until Column 2 reaches a width of 200 and the application hangs.

@SamBent, you suggest [here](https://github.com/Microsoft/dotnet/issues/393#issuecomment-307202219) that a similar issue was resolved in 4.7.1. The workaround mentioned (`StarDefinitionsCanExceedAvailableSpace=true`) does work around this issue as well.

Breaking the application shows the main thread sitting at: 	 	 	 	 	`PresentationFramework.dll!System.Windows.Controls.Grid.ResolveStarMaxDiscrepancy(System.Windows.Controls.DefinitionBase[] definitions, double availableSize)`

```
<Window x:Class="GridMinWidthRepo.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Height="200" Width="500">
    <Grid Margin="0,20,0,0">
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="100" />
            <ColumnDefinition Width="*" MaxWidth="20" />
            <ColumnDefinition Width="*" MinWidth="200" />
        </Grid.ColumnDefinitions>
        <TextBox Grid.Column="0" HorizontalAlignment="Stretch" />
        <TextBox Grid.Column="2" HorizontalAlignment="Stretch"
                 Text="{Binding RelativeSource={RelativeSource Self}, Path=ActualWidth, Mode=OneWay}"/>
    </Grid>
</Window>
```

**Comment by SamBent** [comment] 2018-01-27 02:09
I don’t repro this hang in 4.7.1 (only in 4.7).   Are you sure you’ve got the right runtime?

**Comment by brinko99** [comment] 2018-01-27 04:09
@SamBent Hmm... yes, I believe so.

Here's a short video demonstrating the framework version and issue:
https://drive.google.com/file/d/1lqtf74GKra5hmI-rr8N2n2P3Y6GexDsF/view?usp=sharing

Window 10 Enterprise, 10.0.14393 Build 14393
Visual Studio Pro 2017 15.5.4

This is the loaded System.Core.dll:
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.ore.dll
4.7.2558.0 built by: NET471REL1

**Comment by brinko99** [comment] 2018-01-30 17:54
Must have accidentally closed the issue. It is still relevant....

**Comment by brinko99** [comment] 2018-05-04 21:02
I continue to see this issue in the just released 4.7.2. The same behavior is seen as shown in the short video linked to above.

**Comment by EamonHetherton** [comment] 2018-07-19 06:46
We're seeing what I believe is the same issue. 
`<AppContextSwitchOverrides value="Switch.System.Windows.Controls.Grid.StarDefinitionsCanExceedAvailableSpace=true" />` resolves the problem but seems like a workaround for a bug rather than a fix.  Also we seem to only encounter the issue at 120 DPI.

**Comment by steevcoco** [comment] 2018-09-27 11:57
I can reproduce this bug reliably in Framework 4.7.2 ... And it was not hard to hit!

I have created a repository on GitHub with a simple project that will reliably hang. It is here:

https://github.com/steevcoco/Net472SetFinalSizeMaxDiscrepancyHangs

**Comment by SamBent** [comment] 2018-10-05 18:53
@steevcoco - I run your project on 4.7.2 with no problem.   Are you running in 120dpi (or other dpi), like @EamonHetherton?

We have fixed two hangs in Grid:  one from this report that arises when *-columns with Min constraints use up all the available space, and another that arises only in high dpi when UseLayoutRounding=true and min widths for *-columns cause unfavorable rounding decisions.   They have the same callstack, but different root causes;   both are fixed in 4.8.   EamonHetherton probably hit the second bug, and perhaps you did too.

I doubt that the DP is relevant.  More likely by commenting out the DrawingGrid you changed the effective min-widths in a way that produces better rounding decisions.   The second bug is highly sensitive - changing any of the widths involved by even a tiny fraction of a pixel can change the rounding decisions and go from hang to no-hang (or vice-versa).

**Comment by steevcoco** [comment] 2018-10-07 13:49
@SamBent - I CAN 100% reliably crash with that project on this machine ...

There IS display SCALING enabled here: the Windows Text Scaling is set to 116%. This is a 3K display --- 120 dpi, 2880x1620, 60 Hz. And I HAVE just confirmed that disabling the SCALING DOES cure it!

This is a laptop with two display cards; and I'm also reasonably sure I HAVE seen it happen on both display drivers (plugged in and unplugged). It will hang every time.

Please note also: it seems TOUCHY! Previously, I had to ONLY disable the "DrawingGrid" instance that is inside a Border ... But just now I ran again and that didn't work! I have to disable BOTH instances of the "DrawingGrid" to get it to run! (While text scaling is enabled.) --- Disabling Windows Text Scaling seems to let it run normally with both instances in the window.

**Comment by SamBent** [comment] 2019-02-13 19:47
For the benefit of people with similar problems who get to this issue, here's a summary.   For simplicity it refers to 'columns' and 'widths', but everything also applies to 'rows' and 'heights'.

.Net 4.7 included a new algorithm for allocating space to columns in a Grid declared with '*' in their widths.  The new algorithm improved over the old one in many ways, chiefly to fix over-allocation:  columns receiving so much space that the total width exceeds the width of the Grid itself.   The old algorithm is still available;  there's an app-context switch that chooses between them:
   Switch.System.Windows.Controls.Grid.StarDefinitionsCanExceedAvailableSpace
This defaults to 'false' for apps that target .Net 4.7 and above, and to 'true' for earlier target versions.

Unfortunately the new algorithm had three bugs (that we know of), all resulting in infinite loops.

1. Two *-columns, both declaring MinWidth and MaxWidth; content doesn't exceed MaxWidth;  first MinWidth plus any other fixed or Auto columns exceeds available width.  [442027, Issue [393](https://github.com/Microsoft/dotnet/issues/393)].
2. The *-columns with min constraints use up all the available space.  [560609, Issue [604](https://github.com/Microsoft/dotnet/issues/604)]
3. High DPI; UseLayoutRounding is true; *-columns acquire minimum width from a child with ColumnSpan > 1; floating-point roundoff has unfortunate outcome.  [619978].

The first bug was fixed in .Net 4.7.1, the other two are fixed in .Net 4.8.  If you can't upgrade your .Net runtime, all of them can be avoided using the switch to revert to the old algorithm, although you'd get its bugs as well (such as the over-allocation bug).

The third bug is very sensitive.  Changing the widths by a millionth of a pixel can fix the loop (or cause it to happen).  Changing the DPI scale can flip the bug.  Even running on a different machine can flip the bug, presumably because the floating-point hardware gives slightly different results.

**Comment by RickStrahl** [comment] 2019-02-15 09:51
@SamBent Thanks for the succinct summary here. That's really helpful and hopefully will make this discoverable.

It would be nice if this could get patched for 4.7 somehow since that is currently the widest use case for .NET runtime users and way to easy to miss.

**Comment by DarkCloud14** [comment] 2019-11-21 13:57
It's a long time since the last activity here but there are still issues with the new algorithm even in .NET 4.8, right?

At least we experience an infinite loop/hang issue in an two applications developed for our company and we can only get it fixed by either setting UseLayoutRounding to false for the Grids that are shown if this issue occurs or use the AppContext StarDefinitionsCanExceedAvailableSpace instead.
The Grids have ColumnDefinitions/RowDefinitions and use star sizing at some columns/rows.
We can also switch the scaling from 175% to 150% or 200% to get rid of it but in that case it could happen on another control..

For now we will use the AppContext switch, switching off LayoutRounding isn't an option.
Here is a picture of the call stack when this situation occurs and I pause it.
![GridStarHangCallstack](https://user-images.githubusercontent.com/314477/69341667-47ddb400-0c6a-11ea-942b-28e1253443eb.png)

The picture above was taken with dnSpy as the problem is occuring on Surface 4 Pro tablets used in production and I don't have the same tablet at my desk and didn't want to install VS remote debugging tools on one of the affected tablets used in production, at least not yet...

Unfortunately I wasn't able to create an example application that reproduces the problem to upload it here. The only other thing I can say is, that it's not just occurring in the control I took the screenshot with but we also had the problem in a different control at another factory where they use a Dell tablet with 4k resolution and 225% scaling.
All systems with the problem use Windows 10 1809 or newer, I even have the problem on a system that I just updated to Windows 10 1909 and the latest cumulative update for Windows 10 and .NET Framework installed.

The applicaiton currently targets .NET 4.7.2 but after I found this bug report I recompiled the application targeting .NET 4.8 and I still have this problem!

**Comment by SamBent** [comment] 2019-11-21 18:15
@DarkCloud14 - yours looks like a different problem.  Your callstack doesn't even mention Grid, but does mention ScrollViewer.OnLayoutUpdated (which this problem didn't).  That suggests that the ScrollViewer is getting a constant stream of requests to scroll.  The new algorithm is clearly a factor, but is not directly responsible for your hang.

I recommend you open a new issue here (or open a case with CSS if you have a support contract).  Attach a repro app if you can.  If not, the next best thing would be a [TimeTravelDebug](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/time-travel-debugging-overview) trace of a few iterations of the loop.  

We've had no reports of any problems with the new algorithm since fixing this one.  BTW, the fix was backported to 4.7.x in June - see [this announcement](https://devblogs.microsoft.com/dotnet/net-framework-june-2019-preview-of-quality-rollup/).

**Comment by DarkCloud14** [comment] 2019-11-21 18:50
@SamBent thanks for the reply and information, you're right, now that I look at it again there isn't any trace of a grid in the callstack.

I'll first try to create a repro app again (or use TimeTravelDebug if I can't create a repro app) and then do one of the next steps you mentioned by opening a new issue here or open a case with CSS if we've have an active support contract, I've to check that first...

Also thanks for the info that this fix was backported as I must've overlooked that.

**Comment by kalaskarsanket** [comment] 2020-12-07 20:26
This issue has not got any input for long time and we have changed were issues are tracked. If this is still an issue kindly raise a new issue in the appropriate repo as mentioned in [dotnet/1275](https://github.com/microsoft/dotnet/issues/1275)

**Closed by kalaskarsanket** 2020-12-07 20:26 UTC
