### ISSUE TITLE
.NET Framework 4.7.1 via WSUS breaking things

### ISSUE THREAD

**Issue by jwckauman** [microsoft/dotnet#602] opened 2018-01-17 15:39 UTC
We allowed .NET Framework 4.7.1 to install via WSUS this past week and it broke at least three applications.1. Cherwell Service Desk; 2. SQL Server Management Studio; 3. Visual Studio 2015.  We used the workaround to get them working (uninstalled Security/Quality update and installed Security-Only update).  Is there going to be a new Security/Quality update going out via WSUS shortly?

**Comment by jnm2** [comment] 2018-01-18 00:51
The .NET team would probably appreciate some detail on the three breaks.

**Comment by jwckauman** [comment] 2018-01-22 15:48
For the application called "Cherwell Service Desk", we saw this in the application Event log

Faulting application name: Trebuchet.App.exe, version: 9.1.1.1663, time stamp: 0x59386c7f
Faulting module name: KERNELBASE.dll, version: 6.1.7601.24009, time stamp: 0x5a52408a
Exception code: 0xe0434352
Fault offset: 0x000000000001a06d
Faulting process id: 0x2d1c
Faulting application start time: 0x01d392f8a8e34cfc
Faulting application path: C:\Program Files (x86)\Cherwell Software\Cherwell Service Management\Trebuchet.App.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: ece48d58-feeb-11e7-b127-4c3488d9ddc9

**Comment by jwckauman** [comment] 2018-01-22 15:48
and this...

Application: Trebuchet.App.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileFormatException
   at MS.Internal.FontFace.CompositeFontParser.Fail(System.String, System.Exception)
   at MS.Internal.FontFace.CompositeFontParser.ParseFontFamilyCollectionElement()
   at MS.Internal.FontFace.CompositeFontParser..ctor(System.IO.Stream)

Exception Info: System.IO.FileFormatException
   at MS.Internal.FontFace.CompositeFontParser.Fail(System.String, System.Exception)
   at MS.Internal.FontFace.CompositeFontParser..ctor(System.IO.Stream)
   at MS.Internal.FontCache.FamilyCollection+SystemCompositeFonts.GetCompositeFontFamilyAtIndex(Int32)
   at MS.Internal.FontCache.FamilyCollection.GetFontFamilies(System.Uri, System.String)
   at System.Windows.Media.Fonts.CreateFamilyCollection(System.Uri, System.Uri, System.String)
   at System.Windows.Media.Fonts..cctor()

Exception Info: System.TypeInitializationException
   at DevExpress.Xpf.Editors.Settings.FontUtility.GetSystemFontFamilies()
   at DevExpress.Office.Internal.FontManager.GetFontFamilyNames()
   at DevExpress.Office.Drawing.TypefaceResolver..cctor()

Exception Info: System.TypeInitializationException
   at DevExpress.Office.Drawing.TypefaceResolver..ctor()
   at DevExpress.Office.Drawing.WpfFontInfo.CreateFont(DevExpress.Office.Drawing.FontInfoMeasurer, System.String, Int32, Boolean, Boolean, Boolean, Boolean)
   at DevExpress.Office.Drawing.WpfFontCache.CreateFontInfoCore(System.String, Int32, Boolean, Boolean, Boolean, Boolean)
   at DevExpress.Office.Drawing.FontCache.CreateFontInfo(Int64, System.String, Int32, Boolean, Boolean, Boolean, Boolean)
   at DevExpress.Office.Drawing.FontCache.CalcFontIndexCore(System.String, Int32, Boolean, Boolean, DevExpress.Office.CharacterFormattingScript, Boolean, Boolean)
   at DevExpress.Office.Drawing.FontCache.CalcNormalFontIndex(System.String, Int32, Boolean, Boolean, Boolean, Boolean)
   at DevExpress.XtraRichEdit.Model.TextRunBase.CalculateFontIndexCore(System.String)
   at DevExpress.XtraRichEdit.Model.TextRunBase.get_FontCacheIndex()
   at DevExpress.XtraRichEdit.Layout.Engine.BoxInfo.GetFontInfo(DevExpress.XtraRichEdit.Model.PieceTable)
   at DevExpress.XtraRichEdit.Layout.Engine.BoxMeasurer.MeasureParagraphMark(DevExpress.XtraRichEdit.Layout.Engine.BoxInfo)
   at DevExpress.XtraRichEdit.Layout.Engine.CharacterFormatterStateBase.CreateParagraphMarkBoxInfo()
   at DevExpress.XtraRichEdit.Layout.Engine.CharacterFormatterStateBase.FinishParagraph()
   at DevExpress.XtraRichEdit.Layout.Engine.CharacterFormatterStateBase.GetNextState()
   at DevExpress.XtraRichEdit.Layout.Engine.CharacterFormatterStartState.ContinueFormat()
   at DevExpress.XtraRichEdit.Layout.Engine.ParagraphCharacterFormatter.FormatParagraph(DevExpress.XtraRichEdit.Layout.Engine.ParagraphCharacterIterator)
   at DevExpress.XtraRichEdit.Layout.Engine.ParagraphCharacterFormatter.Format(DevExpress.XtraRichEdit.Layout.Engine.ParagraphCharacterIterator)
   at DevExpress.XtraRichEdit.Layout.Engine.BeginParagraphFormatting.EnsureParagraphBoxes()
   at DevExpress.XtraRichEdit.Layout.Engine.BeginParagraphFormatting.FormatNextRow()
   at DevExpress.XtraRichEdit.Layout.Engine.DocumentFormatter.FormatNextRow()
   at DevExpress.XtraRichEdit.Layout.Engine.BackgroundFormatter.PerformPrimaryLayoutCore()
   at DevExpress.XtraRichEdit.Layout.Engine.BackgroundFormatter.HandleCommand(Int32)
   at DevExpress.XtraRichEdit.Layout.Engine.BackgroundFormatter.Worker(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)

**Comment by jwckauman** [comment] 2018-01-22 15:49
...and this

Thread: Thread_15
Message: Unhandled Exception
Exception: 
[System.TypeInitializationException] The type initializer for 'DevExpress.Office.Drawing.TypefaceResolver' threw an exception.
   at DevExpress.Office.Drawing.TypefaceResolver..ctor()
   at DevExpress.Office.Drawing.WpfFontInfo.CreateFont(FontInfoMeasurer measurer, String fontName, Int32 doubleFontSize, Boolean fontBold, Boolean fontItalic, Boolean fontStrikeout, Boolean fontUnderline)
   at DevExpress.Office.Drawing.WpfFontCache.CreateFontInfoCore(String fontName, Int32 doubleFontSize, Boolean fontBold, Boolean fontItalic, Boolean fontStrikeout, Boolean fontUnderline)
   at DevExpress.Office.Drawing.FontCache.CreateFontInfo(Int64 hash, String fontName, Int32 doubleFontSize, Boolean fontBold, Boolean fontItalic, Boolean fontStrikeout, Boolean fontUnderline)
   at DevExpress.Office.Drawing.FontCache.CalcFontIndexCore(String fontName, Int32 doubleFontSize, Boolean fontBold, Boolean fontItalic, CharacterFormattingScript script, Boolean fontStrikeout, Boolean fontUnderline)
Inner exc: 
[System.IO.FileFormatException] No FontFamily element found in FontFamilyCollection that matches current OS or greater: Windows7SP1
   at MS.Internal.FontFace.CompositeFontParser.Fail(String message, Exception innerException)
   at MS.Internal.FontFace.CompositeFontParser.ParseFontFamilyCollectionElement()
   at MS.Internal.FontFace.CompositeFontParser..ctor(Stream fileStream)

**Comment by jnm2** [comment] 2018-01-22 16:11
I believe this is addressed by https://github.com/dotnet/announcements/issues/53 and a duplicate of https://github.com/Microsoft/dotnet/issues/599. What happens when you try the workarounds?

**Comment by jwckauman** [comment] 2018-01-22 17:06
The workaround that said remove KB4055002 worked.  We haven't had a chance to try the latest suggestions (i believe a fixit tool has been provided).  If we run into this issue again we will try the fixit tool.

**Comment by jnm2** [comment] 2018-01-25 13:21
https://github.com/dotnet/announcements/issues/54 was just released, so this issue can probably be closed.

**Comment by kalaskarsanket** [comment] 2020-12-07 20:31
Closing this issue as mentioned above. We have changed were issues are tracked. If this is still an issue kindly raise a new issue in the appropriate repo as mentioned in [dotnet/1275](https://github.com/microsoft/dotnet/issues/1275)

**Closed by kalaskarsanket** 2020-12-07 20:31 UTC
