### ISSUE TITLE
"csc.exe" exited with code -2146232797.

### ISSUE THREAD

**Issue by matiasdd** [Microsoft/dotnet#509] opened 2017-10-12 07:59 UTC
The following program results in an internal compiler error:

```
    class Program
    {
        public void A(object data)
        {
            lock (this)
            {
                void B() => Send(data);
                void C() => B();
                C();
            }
        }

        void Send(object data)
        {
        }
    }
```

Outputs:
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error MSB6006: "csc.exe" exited with code -2146232797.

Removing the `lock` solves the problem.
Removing the capture of `data` solves the problem.
Removing the method `C`  resolves the problem.

**Comment by svick** [comment] 2017-10-12 11:25
This looks like duplicate of https://github.com/dotnet/roslyn/issues/19033, which is already fixed in Roslyn master.

Indeed, as expected for that issue, [your code throws `KeyNotFoundException` on the release version of Roslyn](https://sharplab.io/#v2:CYLg1APgBDUAICZ4EYDsBYAULKBvLOOcAzPACxQCCAFAPYBGAVgKYDGALlMAIbvcCUBQjHzZhhADa1WAayjV2ACwCWAZ0FjxsUVq1wKAIWr8oAXgB8UAMrMAdsGo8+/ANxDdhfVADCxs5aNXdw9YXyDNXQBfYJxozBjYLxt7OiY2TicBBJFsqDjYoA==), but [compiles fine on latest Roslyn from master](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ACX2ACATAQIwDsAsAFB7YDe1tt+AzAQCzYCCAFAPbAAVnADGMbCggwIASkZNcDGgqYAbPiIDW2HjAAWASyhzlKvErNn8nAEI8Z2ALwA+bAGU4AOxQ9J0mQDc8pZM1tgAwvZOrnaBwSF4kXGmlgC+8bTpVBl4YR7e/EKi4n6yOYrl2FmZQA=).

**Closed** 2017-10-12 12:33 UTC
