### ISSUE TITLE
.NET 4.7 Performance Degrade

### ISSUE THREAD

**Issue by peter----** [Microsoft/dotnet#492] opened 2017-09-27 23:53 UTC
All of Our PCs are WIN7. I do not have WIN10 to test it.

Our desktop C# application (mainly scientific calculations):  performance degrades a lot in .NET 4.7 for the first iteration.
Later iterations work normally.
           0.1 second for the first iteration in .NET 4.6/4.5/4.0
           14 seconds for the first iteration in .NET 4.7

The 32 bit run in .NET 4.7 is OK.
The 64 bit run in debug version is OK.
The 64 bit run in release version without 'Optimize Code" check is OK.

It only happens when .NET 4.7 Release version with "Optimize Code" checked.

It happens in our application in multiple people and multiple PC.
It always happen in the same place when it tries to call a very normal function, but before the first instruction in the called function.

We have used VS Performance Profiling to see what is going on during the 14 seconds: it shows "No Call Tree Data Is Available."

The memory usage is very low for the application. So I do not think memory is an issue here.

I also tried to enforce memory garbage collection before the function. 
The problem still stays the same.

Any ideas?

**Comment by Petermarcu** [comment] 2017-10-15 06:31
@brianrob any ideas what additional information can be gathered to help root cause?

**Comment by brianrob** [comment] 2017-10-16 05:10
Yes.  The first step here is to collect ETW traces of the good and bad cases.  The goal is to capture equivalent work in both cases so that we can compare the difference in resources used to accomplish the same amount of work in both cases.

It sounds like you can reproduce this on the same bitness (64-bit) with and without Optimized Code checked.  If you can use these as the two cases that would be good.

To collect the traces, I recommend using PerfView: https://www.microsoft.com/en-us/download/details.aspx?id=28567.

To collect, simply run "PerfView.exe collect", once it starts, run your scenario, and then click stop.  It will produce a file called PerfViewData.etl.zip.

Once you have the two cases - good and bad - just put them up somewhere that I can take a look, and I can help diagnose the issue.  You can also reach me directly at brianrob at microsoft dot com.

**Comment by richlander** [comment] 2017-11-13 05:46
@peter---- is this still a problem? Please get back to us with some more info. Otherwise, we'll close the issue.

**Comment by richlander** [comment] 2017-11-29 06:26
Hey @peter---- , are you still tracking this?

**Comment by peter----** [comment] 2017-11-29 06:51
Hi,
The issue is resolved at the new 4.7 build.Thanks,Peter

**Closed** 2017-11-29 06:55 UTC
