### ISSUE TITLE
Manual Garbage Collecting

### ISSUE THREAD

**Issue by SiamandMaroufi** [microsoft/dotnet#631] opened 2018-02-23 08:04 UTC
.net platform has no manual gc and in a large scale applications we've got a lot of GC hit , and GC.Collect() is not a good option for this thing

**Comment by mcosmin222** [comment] 2018-02-27 15:47
GC.Collect is the manual way of doing GC. Perhaps you mean having a "delete" keyword which causes an object and its reference tree to be collected instantly?

**Comment by svick** [comment] 2018-02-27 16:09
There are many ways to mitigate performance issues caused by excessive garbage collection, like using `struct`s instead of `class`es, [object pooling](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.arraypool-1?view=netcore-2.0), and the recent and upcoming work on [`Span<T>`](https://blogs.msdn.microsoft.com/dotnet/2017/11/15/welcome-to-c-7-2-and-span/) and `Memory<T>` (possibly combined with `unsafe` code and allocating native memory).

Also, avoiding heap allocations for temporary objects is on the radar of the CLR team (https://github.com/dotnet/coreclr/issues/1784).

Do you have some specific proposal that's not addressed by any of the above?

**Comment by Petermarcu** [comment] 2018-03-12 03:12
@Maoni0 as FYI

**Comment by kalaskarsanket** [comment] 2021-01-05 21:24
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275). You can also check our [roadmap](https://github.com/dotnet/core/blob/05d6baa1d41e9b410a31d66aa7197bf24840dfcb/product-roadmap/current.md). The roadmap will be eventually updated for .NET 6

**Closed by kalaskarsanket** 2021-01-05 21:24 UTC
